#!/bin/bash
# get branch name
BRANCH="$(git symbolic-ref HEAD 2>/dev/null)" ||
BRANCH="(unnamed branch)"     # detached HEAD
BRANCH=${BRANCH##refs/heads/}

if ! [[ $BRANCH =~ .*-[0-9]* ]]
then
echo "Branch doesn't match JIRA issue format (.*-[0-9]*). Automaticat commit message will not be generated"
exit 0
fi

if [[ -z $2 ]]
then
MESSAGE=`curl -s -X GET https://www.mulesoft.org/jira/rest/api/latest/issue/$BRANCH |  python -c 'import sys, json; print json.load(sys.stdin)["fields"]["summary"]'`
COMMIT_MESSAGE="$BRANCH: $MESSAGE"
echo $COMMIT_MESSAGE >> $1
else
echo "$BRANCH: $(cat $1)" > $1
fi
